metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "event", "healthcheck", "image", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

- module: postgresql
  enabled: true
  metricsets:
    - database
    - bgwriter
    - activity
  hosts: ["postgres://localhost:5432"]
  username: shilton
  password: shilton15048742W
  period: 10s

- module: elasticsearch
  metricsets: ["node", "node_stats", "cluster_stats", "index"]
  period: 10s
  hosts: ["elasticsearch:9200"]  

# Envio dos dados
output.elasticsearch:
  hosts: ["elasticsearch:9200"]

# Configuração de geração de dashboards
setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true